# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-11-22 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import rest_framework_tracking.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rest_framework_tracking', '0003_change_query_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apirequestlog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='user',
            field=rest_framework_tracking.models.CrossForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
